linters:
  disable-all: true
  enable:
    - bodyclose
    - canonicalheader
    - errcheck
    - errname 
    - errorlint
    - gocheckcompilerdirectives
    - goconst
    - gocritic
    - gocyclo
    - gocyclo
    - gofumpt
    - goimports
    - gosec
    - gosimple
    - govet
    - iface
    - ineffassign
    - ireturn
    - nilnil
    - nolintlint
    - predeclared
    - revive
    - staticcheck
    - stylecheck
    - testifylint
    - typecheck
    - unconvert
    - unused
    - usetesting

linters-settings:
  gofumpt:
    extra-rules: true
  # https://golangci-lint.run/usage/linters/#nolintlint
  nolintlint:
    # Enable to require an explanation of nonzero length after each nolint directive.
    # Default: false
    require-explanation: true
    # Enable to require nolint directives to mention the specific linter being suppressed.
    # Default: false
    require-specific: true