all: false
filename: 'mock_{{ .InterfaceName | snakecase }}.gen.go'
packages:
  github.com/creativefabrica/vat:
    config:
      dir: "vattest/"
      pkgname: "vattest"
    interfaces:
      ValidationClient:
