profile: coverage/cover.out
local-prefix: "github.com/creativefabrica/vat"
threshold:
  package: 70
  total: 70
exclude:
  paths:
    - ^vattest/ # exclude package `vattest`
    - ^example/ # exclude package `example`
